language: node_js

os: linux
dist: bionic

node_js:
  - lts/*

cache: npm

install: npm install

script: echo 'Hello World'

after_success: npm run build

deploy:
  token: $GITHUB_TOKEN

  provider: pages
  strategy: git

  skip_cleanup: true
  local_dir: .
  repo: dhruvkb/issue-projector
  target_branch: master
  committer_from_gh: true
  on:
    branch: develop
